# create kernel/initrd extract
TEMP_KERNEL_INITRD="$(mktemp --directory --suffix '-kernel-initrd')"
cleanup_kernel_initrd() {
  rm --recursive --force "${TEMP_KERNEL_INITRD}" 2>/dev/null || echo "Erreur durant la suppression ${TEMP_KERNEL_INITRD}"
}
trap 'cleanup_kernel_initrd; cleanup_config; cleanup_image;' EXIT

sudo modprobe nbd max_part=8 # cloud image are simple, adapt if necessary
sudo qemu-nbd --connect=/dev/nbd0 "${VM_DISK_FILE}"

# takes a little time to load the partition information
while TEMP_IMAGE_ROOT_PARTITION=$(
  lsblk /dev/nbd0 --json |
    jq --raw-output '.blockdevices[0].children[0].name'
) && [ "${TEMP_IMAGE_ROOT_PARTITION}" == "null" ]; do
  sleep 0.1
done

TEMP_IMAGE_ROOT_PARTITION=/dev/"${TEMP_IMAGE_ROOT_PARTITION}"

set -x

sudo mount -v "${TEMP_IMAGE_ROOT_PARTITION}" "${TEMP_KERNEL_INITRD}"

VMLINUZ=$(basename "${TEMP_KERNEL_INITRD}"/boot/vmlinuz-*)
INITRD=$(basename "${TEMP_KERNEL_INITRD}"/boot/initrd.img-*)
cp -v "${TEMP_KERNEL_INITRD}"/boot/"${VMLINUZ}" "${VMLINUZ}"
cp -v "${TEMP_KERNEL_INITRD}"/boot/"${INITRD}" "${INITRD}"

sudo umount -v "${TEMP_KERNEL_INITRD}"
sleep 0.5
sudo qemu-nbd --disconnect /dev/nbd0
sleep 0.5
sudo modprobe -r nbd

# ACPI OFF or it does not boot
# pit/pic/isa-serial ON or it does not boot
# graphics off and display none, because i want a serial only VM
# loglevel=8 so that we see the last lines the kernel does before giving to init
qemu-system-x86_64 \
  -machine microvm,graphics=off,pit=on,pic=on,isa-serial=on,rtc=on,acpi=off \
  -m "${VM_RAM}" \
  -smp "${VM_CPU}" \
  -enable-kvm \
  -kernel "${VMLINUZ}" \
  -initrd "${INITRD}" \
  -append 'console=ttyS0,115200 root=/dev/vda1 ro loglevel=8' \
  -device virtio-net-device,netdev=net0 \
  -netdev "${NETDEV}" \
  -device virtio-blk-device,drive=disk_img \
  -drive file="${VM_DISK_FILE}",format=qcow2,if=none,id=disk_img \
  -device virtio-blk-device,drive=disk_cfg \
  -drive file="${CONFIGDRIVE_ISO}",format=raw,if=none,id=disk_cfg,read-only=on \
  -display none \
  -serial mon:stdio

# Does not work with virtio_mmio, because the debian kernel is compiled with VIRTIO_MMIO as a module,
# instead of compile inside the kernel, and it is only when it is compiled it that it honors the
# command line parameters : [0.000000] Command line: ...
#    virtio_mmio.device=512@0xfeb00e00:12
#    virtio_mmio.device=512@0xfeb00c00:11
#    virtio_mmio.device=512@0xfeb00a00:10
# rmmod virtio_mmio
# ls /usr/lib/modules/6.12.105+deb13-cloud-amd64/kernel/drivers/virtio/virtio_mmio.ko.xz
# modprobe virtio_mmio ...

# tested on a pc machine with same image to get more information
# # modinfo  virtio_mmio
# filename:       /lib/modules/6.12.105+deb13-cloud-amd64/kernel/drivers/virtio/virtio_mmio.ko.xz
# license:        GPL
# description:    Platform bus driver for memory mapped virtio devices
# author:         Pawel Moll <pawel.moll@arm.com>
# alias:          of:N*T*Cvirtio,mmioC*
# alias:          of:N*T*Cvirtio,mmio
# alias:          acpi*:LNRO0005:*
# depends:
# intree:         Y
# name:           virtio_mmio
# retpoline:      Y
# vermagic:       6.12.105+deb13-cloud-amd64 SMP preempt mod_unload modversions
# sig_id:         PKCS#7
# signer:         Build time autogenerated kernel key
# sig_key:        45:98:D6:26:A4:7B:7A:24:CC:7C:A5:02:57:DB:55:F8:86:E3:A2:D9
# sig_hashalgo:   sha256
# signature:      30:66:02:31:00:E3:BC:78:DC:C8:8B:28:A9:FE:65:18:B7:DF:32:17:
# 		8F:41:33:19:65:86:F4:82:15:52:83:C7:37:9E:7A:79:36:35:29:EA:
# 		04:E3:F1:6C:E3:8C:1A:6F:B9:2B:27:E0:D5:02:31:00:E2:CC:D9:78:
# 		32:ED:A9:33:E9:47:AB:F3:2E:3E:A6:9B:35:2B:D7:D0:FB:D2:96:65:
# 		AB:9A:E9:39:C5:AD:F1:2E:24:09:02:44:79:CB:EF:83:6A:13:ED:80:
# 		17:81:72:19
# root@sandbox:~# zcat /proc/config.gz 2>/dev/null | grep VIRTIO_MMIO
# root@sandbox:~# grep VIRTIO_MMIO /boot/config-6.12.105+deb13-cloud-amd64
# CONFIG_VIRTIO_MMIO=m
# # CONFIG_VIRTIO_MMIO_CMDLINE_DEVICES is not set

# so microvm relies completely on this feature, cannot work with this image as is
# next steps :
# - switch back to pc
# - try q35
# - compile own kernel
# - use already made microvm kernel
